### ISSUE TITLE
hyprctl returns "Invalid Dispatcher" when calling overview:toggle

### ISSUE THREAD

**Issue by Jacobacon215** [KZDKM/Hyprspace#104]
Similar to #5, but I haven't been as lucky with a quick fix.
> Next time please do not hesitate to reopen the issue when reporting under a closed one as I could not receive notifications from closed issues.

`❯ hyprpm list`
 `→ Repository Hyprspace:`
`  │ Plugin Hyprspace`
`  └─ enabled: true`

`❯ hyprctl dispatch overview:toggle`
`Invalid dispatcher`

As of now, `hyprpm update`, `hyprpm reload`, and `hyprpm disable`/`hyprpm enable` have not done anything for me. The issue I'm opening an issue because all similar reported problems seemed to be fixed by various commits sometime in the past as opposed to user intervention. That said, though, I am pretty new to hyprland, so if I've missed something obvious please let me know. Thanks a bunch!

**Comment by myamusashi** [comment]
I can't reproduce. What hyprland u use right now? -git or release?

**Comment by smathles** [comment]
Could reproduce, however `hyprpm reload` fixed it. No issues there for me.

**Comment by myamusashi** [comment]
It's clear that the plugin hasn't been reloaded or you're using the -git version and if you update hyprland, you should also update the plugin.

**Comment by Jacobacon215** [comment]
> I can't reproduce. What hyprland u use right now? -git or release?

I'm using extra/hyprland 0.44.1-2, which is the most updated version of release according to my pacman.

> It's clear that the plugin hasn't been reloaded or you're using hyprland-git version and if you update hyprland, you should also update the plugin.

I reinstalled hyprland as part of my initial troubleshooting, and I've run `hyprpm update`. I just reran `hyprpm update` then `hyprpm reload` and tried rerunning the dispatcher, to no avail.

**Comment by KZDKM** [comment]
Always do `hyprpm reload`, add it to your `exec-once`. I don't know why this is necessary to activated enabled plugin but thats what I have always been doing.

> I reinstalled hyprland as part of my initial troubleshooting, and I've run hyprpm update. I just reran hyprpm update then hyprpm reload and tried rerunning the dispatcher, to no avail.

That means either you havent actually enabled the plugin, or one of the handlers in the plugin ran into an error and hyprland has to unload it. Check for `unloading` keyword in your log to see if the latter is the case. Though I've also been on 0.44.1-2 and the plugin ran fine for me so I dont think it should crash.

**Comment by Jacobacon215** [comment]
Adding `hyprpm reload` to my `exec-once` and restarting hyprland seems to have solved the problem! Thank you very much for the help. BTW, I don't have a touchscreen, so don't worry about bughunting that.
