### ISSUE TITLE
Crash on 0.45 hyprland

### ISSUE THREAD

**Issue by myamusashi** [KZDKM/Hyprspace#107]
[ERR] [14:23:40.096898882] Unable to search for function "mouse": no symbols found in binary (is "nm" in path?)
[ERR] [14:23:40.097202891] Unable to search for function "renderWindow": no symbols found in binary (is "nm" in path?)

**Comment by myamusashi** [comment]
https://github.com/hyprwm/Hyprland/issues/8410

**Comment by KZDKM** [comment]
Shouldn't be a problem, the plugin does not utilize any function hook. Currently the pathing is very broken on hyprland and hyprpm does not work either. Checking out the tagged v0.45.0 branch works fine for me.
