### ISSUE TITLE
Feature request to hide special workspaces

### ISSUE THREAD

**Issue by cunbidun** [KZDKM/Hyprspace#11]
Hi, thanks for the great plugin!

One small suggestion - it would be nice to have an option to hide certain workspaces in the overview (special workspaces). Maybe allow users to provide a fixed list of workspaces they want to see. That way, no new workspaces could be created in the overview, but users could still move items between the listed workspaces.

Let me know if something like that would be feasible to add. It would help keep the overview panel focused on just the workspaces users need access to.

**Comment by KZDKM** [comment]
Noted, I dont use special workspaces in my workflow so I have not considered it during initial development. Blacklisting / whitelisting workspaces and layers to hide is a planned feature. `plugin:overview:showNewWorkspace = false` and `plugin:overview:showEmptyWorkspaces = false` might be a temporary workaround, refer to readme.

**Comment by KZDKM** [comment]
Resolved by https://github.com/KZDKM/Hyprspace/commit/c91364c4f85267a2e949b766a6ba517e7fb61310. Thanks for the suggestion!
