### ISSUE TITLE
[Bug] Building fails manually and via hyprpm

### ISSUE THREAD

**Issue by KadirBalku** [KZDKM/Hyprspace#112]
Hello there, yesterday everything worked fine today i tried to swipe my touch pad and nothing happened.
Tried to figure out whats wrong and using `hyprctl dispatch overview:toggle` in my terminal outputted "invalid dispatcher".
So i removed Hyprspace with hyprpm and tried to reinstall with hyprpm add which always outputted "build failed" (verbose option didnt help to find an issue). Next i tried to do a manual install. cloned the repo and used `make all` in the repos folder and again the build failed.
![hyprspace_build_error](https://github.com/user-attachments/assets/6c9a10ce-a038-45a8-983f-456c98bd2530)

*edit: #111 related to this if i am not mistaken -> after checking what has changed i think the issue is on my side and i need to wait for an hyprland update in the arch repos or do a manual build

**Comment by myamusashi** [comment]
Ah yes this is for the -git version if you want it, you can check the git log before that latest commit and git checkout <log>.
