### ISSUE TITLE
Opening the overview loses resize information

### ISSUE THREAD

**Issue by Namnodorel** [KZDKM/Hyprspace#122]
When two windows are opened in the same workspace and were resized to take up different amounts of space than 50/50, opening and closing the overview resets them to taking up the screen 50/50.

Note that while the overview is active, the information is still there, but once it is closed they revert back to not being resized.

**Comment by myamusashi** [comment]
I can't repro this, what is your config?

**Comment by Namnodorel** [comment]
Can't reproduce either anymore, will close until I can again.
