### ISSUE TITLE
I Get `Invalid dispatcher` when trying to do the bindings for overiew:toggle.

### ISSUE THREAD

**Issue by Nicknamely** [KZDKM/Hyprspace#124]
I know I am doing it wrong since this is the best have come with 
```conf
bind = $mainMod, tab, overview:toggle
```
Also
![image](https://github.com/user-attachments/assets/0646dec0-bcef-44d3-b381-5c7fb6e708ae)

**Comment by KZDKM** [comment]
what is the output of hyprctl version

**Comment by Nicknamely** [comment]
![image](https://github.com/user-attachments/assets/99b3ea14-0903-4edd-84a6-cfe9d332df6e)

**Comment by myamusashi** [comment]
Huh, that's weird. I can dispatch the overview. Did you reinstall it?

**Comment by Nicknamely** [comment]
I am currently updating to latest-git.

**Comment by Nicknamely** [comment]
Still same issue.

**Comment by myamusashi** [comment]
https://github.com/KZDKM/Hyprspace/issues/104 if this can't help you, then idk

**Comment by KZDKM** [comment]
Might be some recent breaking change that causes one of the handlers to crash, I will look into it when I have time.

**Comment by uxodb** [comment]
@Nicknamely is the plugin listed when you run `hyprctl plugins list` ?

**Comment by Nicknamely** [comment]
I recently updated to the latest commit, and after updating Hyprland and Hyprpm, everything works fine now.

Just switched back to the latest release.  Because I was having some weird dependency conflict.  And I just don't have much use of the plug-in.
