### ISSUE TITLE
Latest update broke overview:toggle

### ISSUE THREAD

**Issue by XclusivVv** [KZDKM/Hyprspace#128]
Your latest update stopped the following from working:

overview:toggle
overview:open
overview:close

Thanks.

![image](https://github.com/user-attachments/assets/926eac38-bafc-4aae-8574-70b8452032ae)

😕

**Comment by myamusashi** [comment]
https://github.com/KZDKM/Hyprspace/issues/124 I don't understand why some people always get these types of errors. Was your Hyprspace successfully build?

**Comment by XclusivVv** [comment]
> #124 I don't understand why some people always get these types of errors. Was your Hyprspace successfully build?

`✔ Hyprland headers OK                                                                                                                                                      
→ Building Hyprspace                                                                                                                                                       
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building plugin(s)[v] shell returned:  -> cd /run/user/1000/hyprpm/x && PKG_CONFIG_PATH="/home/x/.local/share/hyprpm/headersRoot/share/pkgconfig" make all
g++ -shared -fPIC --no-gnu-unique -Wall -g -DWLR_USE_UNSTABLE -std=c++2b -O2 `pkg-config --cflags pixman-1 libdrm hyprland pangocairo libinput libudev wayland-server xkbcommon` src/Input.cpp src/Layout.cpp src/main.cpp src/Overview.cpp src/Render.cpp -o Hyprspace.so
src/main.cpp: In function ‘PLUGIN_DESCRIPTION_INFO pluginInit(void*)’:
src/main.cpp:473:18: error: ‘addDispatcherV2’ is not a member of ‘HyprlandAPI’; did you mean ‘addDispatcher’?
  473 |     HyprlandAPI::addDispatcherV2(pHandle, "overview:toggle", ::dispatchToggleOverview);
      |                  ^~~~~~~~~~~~~~~
      |                  addDispatcher
src/main.cpp:474:18: error: ‘addDispatcherV2’ is not a member of ‘HyprlandAPI’; did you mean ‘addDispatcher’?
  474 |     HyprlandAPI::addDispatcherV2(pHandle, "overview:open", ::dispatchOpenOverview);
      |                  ^~~~~~~~~~~~~~~
      |                  addDispatcher
src/main.cpp:475:18: error: ‘addDispatcherV2’ is not a member of ‘HyprlandAPI’; did you mean ‘addDispatcher’?
  475 |     HyprlandAPI::addDispatcherV2(pHandle, "overview:close", ::dispatchCloseOverview);
      |                  ^~~~~~~~~~~~~~~
      |                  addDispatcher
src/main.cpp: At global scope:
src/main.cpp:328:24: warning: ‘SDispatchResult dispatchCloseOverview(std::string)’ defined but not used [-Wunused-function]
  328 | static SDispatchResult dispatchCloseOverview(std::string arg) {
      |                        ^~~~~~~~~~~~~~~~~~~~~
src/main.cpp:313:24: warning: ‘SDispatchResult dispatchOpenOverview(std::string)’ defined but not used [-Wunused-function]
  313 | static SDispatchResult dispatchOpenOverview(std::string arg) {
      |                        ^~~~~~~~~~~~~~~~~~~~
src/main.cpp:287:24: warning: ‘SDispatchResult dispatchToggleOverview(std::string)’ defined but not used [-Wunused-function]
  287 | static SDispatchResult dispatchToggleOverview(std::string arg) {
      |                        ^~~~~~~~~~~~~~~~~~~~~~
src/Render.cpp: In member function ‘void CHyprspaceWidget::draw()’:
src/Render.cpp:122:248: warning: narrowing conversion of ‘Config::panelBorderWidth’ from ‘int’ to ‘double’ [-Wnarrowing]
  122 |         CBox borderBox = {widgetBox.x, owner->vecPosition.y + (Config::onBottom * owner->vecTransformedSize.y) + (Config::panelHeight + Config::reservedArea - curYOffset.value() * owner->scale) * bottomInvert, owner->vecTransformedSize.x, Config::panelBorderWidth};
      |                                                                                                                                                                                                                                                ~~~~~~~~^~~~~~~~~~~~~~~~
make: *** [Makefile:7: all] Error 1


✖ Plugin Hyprspace failed to build.                                                                                                                                        
  This likely means that the plugin is either outdated, not yet available for your version, or broken.
  If you are on -git, update first
  Try re-running with -v to see more verbose output.

✔ all plugins built                                                                                                                                                        
✔ installed repository                                                                                                                                                     
✔ you can now enable the plugin(s) with hyprpm enable                                                                                                                      
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5 / 5  Done!`

**Comment by XclusivVv** [comment]
✔ Hyprland headers OK                                                                                                                                                      
→ Building Hyprspace                                                                                                                                                       
``` ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building plugin(s)[v] shell returned:  -> cd /run/user/1000/hyprpm/x && PKG_CONFIG_PATH="/home/x/.local/share/hyprpm/headersRoot/share/pkgconfig" make all
g++ -shared -fPIC --no-gnu-unique -Wall -g -DWLR_USE_UNSTABLE -std=c++2b -O2 `pkg-config --cflags pixman-1 libdrm hyprland pangocairo libinput libudev wayland-server xkbcommon` src/Input.cpp src/Layout.cpp src/main.cpp src/Overview.cpp src/Render.cpp -o Hyprspace.so
src/main.cpp: In function ‘PLUGIN_DESCRIPTION_INFO pluginInit(void*)’:
src/main.cpp:473:18: error: ‘addDispatcherV2’ is not a member of ‘HyprlandAPI’; did you mean ‘addDispatcher’?
  473 |     HyprlandAPI::addDispatcherV2(pHandle, "overview:toggle", ::dispatchToggleOverview);
      |                  ^~~~~~~~~~~~~~~
      |                  addDispatcher
src/main.cpp:474:18: error: ‘addDispatcherV2’ is not a member of ‘HyprlandAPI’; did you mean ‘addDispatcher’?
  474 |     HyprlandAPI::addDispatcherV2(pHandle, "overview:open", ::dispatchOpenOverview);
      |                  ^~~~~~~~~~~~~~~
      |                  addDispatcher
src/main.cpp:475:18: error: ‘addDispatcherV2’ is not a member of ‘HyprlandAPI’; did you mean ‘addDispatcher’?
  475 |     HyprlandAPI::addDispatcherV2(pHandle, "overview:close", ::dispatchCloseOverview);
      |                  ^~~~~~~~~~~~~~~
      |                  addDispatcher
src/main.cpp: At global scope:
src/main.cpp:328:24: warning: ‘SDispatchResult dispatchCloseOverview(std::string)’ defined but not used [-Wunused-function]
  328 | static SDispatchResult dispatchCloseOverview(std::string arg) {
      |                        ^~~~~~~~~~~~~~~~~~~~~
src/main.cpp:313:24: warning: ‘SDispatchResult dispatchOpenOverview(std::string)’ defined but not used [-Wunused-function]
  313 | static SDispatchResult dispatchOpenOverview(std::string arg) {
      |                        ^~~~~~~~~~~~~~~~~~~~
src/main.cpp:287:24: warning: ‘SDispatchResult dispatchToggleOverview(std::string)’ defined but not used [-Wunused-function]
  287 | static SDispatchResult dispatchToggleOverview(std::string arg) {
      |                        ^~~~~~~~~~~~~~~~~~~~~~
src/Render.cpp: In member function ‘void CHyprspaceWidget::draw()’:
src/Render.cpp:122:248: warning: narrowing conversion of ‘Config::panelBorderWidth’ from ‘int’ to ‘double’ [-Wnarrowing]
  122 |         CBox borderBox = {widgetBox.x, owner->vecPosition.y + (Config::onBottom * owner->vecTransformedSize.y) + (Config::panelHeight + Config::reservedArea - curYOffset.value() * owner->scale) * bottomInvert, owner->vecTransformedSize.x, Config::panelBorderWidth};
      |                                                                                                                                                                                                                                                ~~~~~~~~^~~~~~~~~~~~~~~~```
make: *** [Makefile:7: all] Error 1


✖ Plugin Hyprspace failed to build.                                                                                                                                        
  This likely means that the plugin is either outdated, not yet available for your version, or broken.
  If you are on -git, update first
  Try re-running with -v to see more verbose output.

✔ all plugins built                                                                                                                                                        
✔ installed repository                                                                                                                                                     
✔ you can now enable the plugin(s) with hyprpm enable                                                                                                                      
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5 / 5  Done!

**Comment by XclusivVv** [comment]
Ah okay... I think it's because I updated yesterday.

```$ hyprland --version
Hyprland 0.46.2 built from branch  at commit 0bd541f2fd902dbfa04c3ea2ccf679395e316887  (version: bump to 0.46.2).
Date: Thu Dec 19 19:26:47 2024
Tag: v0.46.2, commits: 5566
built against:
 aquamarine 0.5.1
 hyprlang 0.6.0
 hyprutils 0.2.6
 hyprcursor 0.1.10
 hyprgraphics 0.1.1


flags set:
debug
```

**Comment by myamusashi** [comment]
> [This pin](https://github.com/KZDKM/Hyprspace/blob/main/hyprpm.toml) only loads hyprland up to 0.45.2

**Comment by bearcatsandor** [comment]
I'm having the same issue. Hyprspace built without errors. I don't understand @myamusashi's comment, as I don't know what a 'pin' is. Are we saying that hyprland 0.46 is incompatible with this plugin at the moment?

**Comment by XclusivVv** [comment]
Here's a better one that works with 0.46.2. --On 06/01/2025, 01:22 "Bearcat M. Şándor" ***@***.***> wrote:

I'm having the same issue. Hyprspace built without errors. I don't understand @myamusashi's comment, as I don't know what a 'pin' is. Are we saying that hyprland 0.46 is incompatible with this plugin at the moment?

**Comment by bearcatsandor** [comment]
Thank you @XclusivVv, but I prefer the look and feel of hyprspace to an expo-like plugin. I'll install that one in the meantime whole I wait for this one though.

**Comment by myamusashi** [comment]
> I'm having the same issue. Hyprspace built without errors. I don't understand @myamusashi's comment, as I don't know what a 'pin' is. Are we saying that hyprland 0.46 is incompatible with this plugin at the moment?

Yes, what i mean by this pin is
```
["a425fbebe4cf4238e48a42f724ef2208959d66cf", "260f386075c7f6818033b05466a368d8821cde2d"], # 0.45.0
["500d2a3580388afc8b620b0a3624147faa34f98b", "260f386075c7f6818033b05466a368d8821cde2d"], # 0.45.1
["12f9a0d0b93f691d4d9923716557154d74777b0a", "260f386075c7f6818033b05466a368d8821cde2d"], # 0.45.2
```
Each line shows which version of Hyprland (the left hash) is compatible with a specific version of Hyprland plugins (the right hash).

**Comment by myamusashi** [comment]
https://github.com/KZDKM/Hyprspace/pull/130
Should be fixed if you're not using the -git version

**Comment by XclusivVv** [comment]
> Thank you @XclusivVv, but I prefer the look and feel of hyprspace to an expo-like plugin. I'll install that one in the meantime whole I wait for this one though.

I took preferred Hyprspace, unfortunately it just didn't update for my version.

Perhaps now it may be updated to work on the latest version of hyprland.

**Comment by bearcatsandor** [comment]
I appreciate the hard work in getting this great plugin fixed so quickly. However, there seems to be an issue on updating:

hyprpm update

✔ Headers up to date.

→ checking for updates for Hyprspace                                                                                             
→ Cloning https://github.com/KZDKM/Hyprspace.git                                                                                 
✔ repository Hyprspace has updates.                                                                                              
→ Building Hyprspace                                                                                                             
✔ found hyprpm manifest                                                                                                          
 ━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2 / 8  Updating Hyprspaceterminate called after throwing an instance of 'toml::v3::ex::parse_error'
  what():  Error while parsing array: expected comma or closing ']', saw '['
[1]    243456 IOT instruction (core dumped)  hyprpm update
