### ISSUE TITLE
Add ability to hide top and overlays layers in overview

### ISSUE THREAD

**Issue by Ligthiago** [KZDKM/Hyprspace#13]
#### Description

I encounter some minor issue - exclusivity of layers kinda doesn't work in overview (AFAIK, correct me if I'm wrong) and all top level layers will sit on top of normal windows, sometimes obscuring the view. Same with on-exclusive overlays, like rofi - they are hidden outside the overview, yes, but still visible in it.
And they're not needed anyway, since layers are now movable.

#### Proposition:
Add `hideTopLayers` option similar to `hideBackgroundLayers`. Probably even better add multiple options for each level.

Nice plugin btw 👍🏻

**Comment by KZDKM** [comment]
Noted. This is a easy feature. Currently working on touchpad gestures and will implement it ASAP.
