### ISSUE TITLE
Ability to disable gestures or switch it's direction

### ISSUE THREAD

**Issue by Ligthiago** [KZDKM/Hyprspace#15]
I'm using `slidevert` workspace animation and gesture to switch workspace are vertical instead default horizontal one. After adding support for gestures in this plugin I can't switch workspace with touchpad anymore because vertical gesture open and close overview. 
Since there are no vertical layout yet, maybe will be nice to add option to just disable gestures from plugin or change it direction via option.

**Comment by KZDKM** [comment]
https://github.com/KZDKM/Hyprspace/commit/9418d8481631db29b5bf7dab3a4d01683662716e should fix.

I am planning to add vertical panel options and by then I will implement horizontal gestures.

**Comment by Ligthiago** [comment]
>should fix.

Yes, fine by me. Thanks
