### ISSUE TITLE
 hyprbars plugin not showing inside overview 

### ISSUE THREAD

**Issue by shadowelite-sec** [KZDKM/Hyprspace#17]
![image](https://github.com/KZDKM/Hyprspace/assets/54718375/34fce900-cd48-43c6-96fa-4c5531439596)

**Comment by KZDKM** [comment]
Does https://github.com/KZDKM/Hyprspace/commit/b0f2b76dcee9d7bd2969bb27de65db939cc9c225 work?

**Comment by shadowelite-sec** [comment]
> Does [b0f2b76](https://github.com/KZDKM/Hyprspace/commit/b0f2b76dcee9d7bd2969bb27de65db939cc9c225) work?

https://github.com/KZDKM/Hyprspace/assets/54718375/3234bd77-2f35-42db-95fd-a0cace203e92

weird :exploding_head:

**Comment by shadowelite-sec** [comment]
> Does [b0f2b76](https://github.com/KZDKM/Hyprspace/commit/b0f2b76dcee9d7bd2969bb27de65db939cc9c225) work?

still look the same!

**Comment by shadowelite-sec** [comment]
https://github.com/KZDKM/Hyprspace/assets/54718375/bec758c7-de2b-4baf-96b5-2c8d76ea4ca5


now overview behaves  strangely

**Comment by KZDKM** [comment]
Forgot to set decorations to true after previous commit. Newest commit should enable it.

I cannot reproduce the problem for blur, but I tried fixing it in the commit anyways, which terminal are you using?

**Comment by shadowelite-sec** [comment]
> Forgot to set decorations to true after previous commit. Newest commit should enable it.
> 
> I cannot reproduce the problem for blur, but I tried fixing it in the commit anyways, which terminal are you using?

**yes now hyprbar is showing inside overview :+1:** 

blur ? but i am not talking blur,  when I open a terminal (I'm using the foot terminal) or any other program. When I switch to the next workspace, half of the window is missing, as shown in this video.

i think its is something related to your  recent commits, i never faced this before

https://github.com/KZDKM/Hyprspace/assets/54718375/243d74a9-2759-4368-8feb-048ea8a5f5f5

**Comment by KZDKM** [comment]
I see, should be a quick fix.

**Comment by KZDKM** [comment]
Checkout the newest commit

**Comment by shadowelite-sec** [comment]
> Checkout the newest commit

Done! 👍 Thanks for responding so quickly
Closing
