### ISSUE TITLE
Hyprspace messing with layers when changing workspace or toggling overview

### ISSUE THREAD

**Issue by matt1432** [KZDKM/Hyprspace#22]
I'm using AGS and my widgets keep replaying their Hyprland animations (layersIn) everytime I switch workspace without the overview open. I also dynamically change the animations and they get reset to the original one for some reason.

It gets even worse when I do open it as you can see here:

https://github.com/KZDKM/Hyprspace/assets/98562002/0db6772e-8f67-46d3-a213-7293c179ecbb

**Comment by KZDKM** [comment]
This doesn't happen with the plugin disabled? Drop your ags dots and I'll see if I could reproduce the problem.

**Comment by matt1432** [comment]
I can confirm this only happens with the plugin. I'll definitely do more testing tomorrow though.

Here's my config: https://github.com/matt1432/nixos-configs/tree/master/modules/ags/config

**Comment by KZDKM** [comment]
Are you using swipe or keybind to dispatchers to change workspace?

**Comment by KZDKM** [comment]
https://github.com/KZDKM/Hyprspace/commit/1859942368375c054c0da0b366d89679c8ced26c for fix.

Test it on your setup.

**Comment by KZDKM** [comment]
Above fixes swiping with overview closed, still fixing animation with overview opened.

**Comment by matt1432** [comment]
Yes those commits fixed all the visual bugs thank you!

And my other problem was just because Hyprland reloaded the default config since it changed so that's on me. Thanks for the quick fixes!
