### ISSUE TITLE
Support `input.kb_options` remap `ESC` 

### ISSUE THREAD

**Issue by chasing-freedom** [KZDKM/Hyprspace#23]
I use `kb_options = caps:swapescape` to swap `ESC`  with `CapsLock`. But I can't exit Hyprspace when i press `CapsLock`. Hyprspace only supports the original key `ESC`.

settings in `hyprland.conf`
```
input {
    kb_layout = us,us
    kb_variant = dvp, 
    kb_model =
    kb_options =grp:toggle,caps:swapescape
    kb_rules =

    follow_mouse = 2

    numlock_by_default = true

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}
```

**Comment by luyu-wu** [comment]
Can't you just set it to the CPSLCK keycode instead?
Pretty sure this is less of a Hyprspace problem than a Hyprland/your config issue!

Of course if you have any suggestions for how you would fix this in Hyprspace I'd be happy to patch it.

**Comment by KZDKM** [comment]
Hyprland implements key swapping by setting xkb keyboard rules. I am not very familiar with the input system and its not very trivial to make this plugin  aware of it. I guess the best course of action is to just to add a new config option for assigning the exit key.

**Comment by chasing-freedom** [comment]
> Hyprland implements(实施) key swapping by setting xkb keyboard rules. I am not very familiar with the input system and its not very trivial(琐碎) to make this plugin aware of it. I guess the best course of action(办法) is to just adding a new config option for assigning(分配) the exit key.

OK. Thank you for your reply.
