### ISSUE TITLE
Workspaces preview not present anymore.

### ISSUE THREAD

**Issue by pbosab** [KZDKM/Hyprspace#34]
on latest git with both hyprland and hyprspace, as in the title the bar displaying the previews is not present anymore.

did I miss some changes in config?

**Comment by KZDKM** [comment]
Could you provide a screenshot / screen capture of whats going on? What is the your output of `hyprctl version`?

**Comment by entailz** [comment]
Here's what it looks like on the newest version of Hyprland.

```
Hyprland, built from branch main at commit 4540d8ccd51e485485af364a951ea7df240585be  (style: fix clang-format).
Date: Wed Apr 24 08:45:54 2024
Tag: v0.39.1-73-g4540d8cc, commits: 4533

flags: (if any)
```

<video src='https://github.com/KZDKM/Hyprspace/assets/132179717/3a24d34f-6bad-409b-af1b-066b776ae9e1' width=180/>

**Comment by pbosab** [comment]
```
Hyprland, built from branch main at commit 34413d1f367b56e17614ee0455b6bf0b61a5aed1  (tokens: fix initial workspace token ignoring special).
Date: Wed Apr 24 03:06:13 2024
Tag: v0.39.1-63-g34413d1f, commits: 4523

flags: (if any)
```

```
monitor=HDMI-A-1,2560x1080,0x0,1
monitor=HDMI-A-2,1920x1080,2560x0,1
```

**Comment by KZDKM** [comment]
Fixed with https://github.com/KZDKM/Hyprspace/commit/983cb8d324e7495e0514820768cbdcecebc5bd2b.
Not our fault, hyprland randomly introduced a change to the plugin API that broke a lot of plugins.
