### ISSUE TITLE
Minor graphic issue 

### ISSUE THREAD

**Issue by Vagahbond** [KZDKM/Hyprspace#39]
Hey, thanks for the great plugin. 

So there's this bug that I suspect is being due to scaling (1.6 on my config). 

The border for the overlay panels shows up much higher than it should, as in attached screenshot : 

![2024-05-07T10:55:35,345799856+10:00](https://github.com/KZDKM/Hyprspace/assets/56230065/7732949b-149f-444c-be89-e244cd905596)

**Comment by luyu-wu** [comment]
Huh, I'm the one who implemented borders so this is probably on me! I'll see what I can do later today after school :)

**Comment by luyu-wu** [comment]
Hyprland broke hyprpm on the recent update too so I can't test my fix properly. The Makefile is also malfunctioning on my laptop (and wouldn't compile correctly for my version anyways).
I can reproduce your error and it is indeed a scaling issue.

https://github.com/luyu-wu/Hyprspace-border/tree/main
This should fix it, but I'm waiting for Hyprland to let me test it before I merge.

Sorry for the delay!

**Comment by Vagahbond** [comment]
Works for me on hyprland 0.40.0 :)

**Comment by luyu-wu** [comment]
Great! That's good to hear :)
I'll just test it one more time once my hashes and hyprpm start working again then merge it.

Thanks for all the help with finding the issue btw!
