### ISSUE TITLE
hyprspace failed to build on v0.40.0-30-gd1ad490c

### ISSUE THREAD

**Issue by shadowelite-sec** [KZDKM/Hyprspace#41]
hyprspace failed to build on v0.40.0-30-gd1ad490c

error log --> [log.txt](https://github.com/KZDKM/Hyprspace/files/15251984/log.txt)

**Comment by KZDKM** [comment]
https://github.com/KZDKM/Hyprspace/commit/87b173843bd104c7064d1700adc3085b7e0841fc
