### ISSUE TITLE
Does not seem to be working

### ISSUE THREAD

**Issue by ThatOneCalculator** [KZDKM/Hyprspace#44]
Despite being installed, enabled, and updated with `hyprpm`, the plugin does not seem as of Hyprland 0.40

![image](https://github.com/KZDKM/Hyprspace/assets/44733677/f0651866-cfce-49e5-ac9d-d1431b903706)

**Comment by luyu-wu** [comment]
0.40 is still WIP (see #43).
Currently you can get it to work by enabling it then reloading hyprland with hyprctl, but it's very buggy.

**Comment by KZDKM** [comment]
I was testing on hyprland-git before hyprland 0.40.0 landed on arch. More breaking changes has happened upstream since 0.40 release and it broke compatibility. I regressed to 0.40 as there is too much going on upstream. Feel free to reopen if issue persists.
