### ISSUE TITLE
(understandably) won't build on 0.4

### ISSUE THREAD

**Issue by entailz** [KZDKM/Hyprspace#48]
i love this plugin, wish there was something i could do to help you fix it but i dont know cpp. do you plan on working on 0.4 hypr plugin api compat? thanks!

**Comment by shadowelite-sec** [comment]
unable to build on  v0.40.0-145-gdf6ebe35

please fix

**Comment by KZDKM** [comment]
Bogged down with schoolwork recently. Will check in a week, use tagged 0.40.0 for now.

**Comment by entailz** [comment]
@KZDKM awesome, excited to have this back! thanks.

**Comment by matt1432** [comment]
> 0.41.0 released! Please fix

The developper will fix it when they'll have the time. Chasing Hyprland's API is a very hard task

**Comment by matt1432** [comment]
This issue should be fixed as of b6f3fc37452ea9b38b5e2662a80fd80aed12018f

**Comment by entailz** [comment]
Yep its fixed :)
