### ISSUE TITLE
Invalid dispatcher

### ISSUE THREAD

**Issue by JarneDel** [KZDKM/Hyprspace#5]
Am i doing something wrong, i'm on the latest version of hyprland but the dispatcher is invalid?
```
$hyprpm list
 → Repository Hyprspace:
  │ Plugin Hyprspace
  └─ enabled: true

$hyprctl dispatch overview:toggle
Invalid dispatcher
```

**Comment by JarneDel** [comment]
Nevermind hyprpm update somehow fixed it, closing

**Comment by KZDKM** [comment]
In case if anyone else bumps into this problem: `hyprpm reload` should also fix this

**Comment by niksingh710** [comment]
@KZDKM 
I have 
```bash
Hyprland, built from branch main at commit a3ca016d42283ce1d2d5ffca40b93123b4290f4b  (cursor-shape: use - instead of _ in shapes).
Date: Thu May 2 20:51:33 2024
Tag: v0.39.1-128-ga3ca016d, commits: 4588

flags: (if any)

```

before this commit hyprspace wasn't getting installed using hyprpm.
Now it is installed and have `enabled` it and also `reloaded` hyprpm still getting `Invalid dispatcher`

**Comment by KZDKM** [comment]
> Now it is installed and have enabled it and also reloaded hyprpm still getting Invalid dispatcher

This is caused by a crash in one of the handlers and is fixed with the most recent commit.

Next time please do not hesitate to reopen the issue when reporting under a closed issue as I could not receive notifications from closed issues.
