### ISSUE TITLE
Hyprland build 0.41 - Plugin crashes on most actions

### ISSUE THREAD

**Issue by e-lain** [KZDKM/Hyprspace#53]
- Main release version of Hyprland 0.41 using current Hyprspace build (6/15/24)
- Dual Monitors
- Discrete GPU only (NVIDIA 3080)

Doing anything except opening and closing the overview (overview:toggle, overview:open, overview:close), will crash the plugin, displaying a banner saying that all “overview:” plugin dispatchers in hyprland.conf do not exist. 

Some examples of crashing: Opening overview, then trying to select another workspace, drag a window to another workspace, dismiss overview by clicking outside the bar, re-order workspaces using overview, etc. Sometimes will crash without any direct interaction with plugin features (seems like pressing $mainMod key, which is involved in calling overview dispatcher, will sometimes cause a crash)

Plugin can be reloaded with hyprpm reload, but will still crash with the same behavior.

**Comment by littleblack111** [comment]
why is it closed as completed? Literally crash on basiclly everything.

*im not saying this plugin is bad. it looks fantastic, but i think you should be solving the issues by fixing bugs in your code instead of just closing it without comment as completed
