### ISSUE TITLE
[OFF TOPIC] not related to this plugin

### ISSUE THREAD

**Issue by shadowelite-sec** [KZDKM/Hyprspace#57]
how you manged to enable bar icons like that
![image](https://github.com/KZDKM/Hyprspace/assets/54718375/a8561224-58a4-4979-a971-09bf4284f36d)

**Comment by KZDKM** [comment]
These are all app specific things. The context menu on vscode is toggled through settings. The window icons are given by the adwaita theme plugin on vscode marketplace and setting icon themes. The terminal is called blackbox.
