### ISSUE TITLE
ESC key behaviour on multiple monitors

### ISSUE THREAD

**Issue by FoxLeader** [KZDKM/Hyprspace#58]
I'm currently using the "overview:toggle, all" bind to open/close the overview on all monitors, but sometimes I have the habit to press ESC to close the overview, which only closes the overview on the current monitor.

It would be possible to have a consistent behaviour depending on the toggle argument? Or maybe through a config option?

Thank you for the plugin, found it yesterday and working great so far!

**Comment by KZDKM** [comment]
Noted. I would push this feature soon!

**Comment by KZDKM** [comment]
Fixed with the newest commit.
