### ISSUE TITLE
Black background on preview

### ISSUE THREAD

**Issue by aacebedo** [KZDKM/Hyprspace#83]
I am using hyprland and hyprspace from NIxpkgs and seeing a strange behavior.

My wallpaper is set using hyprpaper and it seems that hyprspace is not taking it into account.
In addition, the thumbnail in the preview also shows the overview itself.

![image](https://github.com/user-attachments/assets/d9ac42bf-d9b6-48eb-aa70-93e58219a9fb)

What am I missing ?

**Comment by myamusashi** [comment]
Add this to your plugin configuration
workspaceInactiveBackground = rgb(0,0,0)
workspaceActiveBackground = rgba(0,0,0,0)
hideBackgroundLayers = 0/1


![image](https://github.com/user-attachments/assets/ec2bbc41-e7db-4028-a86b-e920d02f888e)

**Comment by aacebedo** [comment]
Thanks for the answer, it fixed the background in each overview but not the background of the panel. The latter is still black.

Can you give me your entire plugin conf? Here's mine:
```
    overview {
            panelColor = rgba(0,0,0,0.5)
            workspaceInactiveBackground = rgb(0,0,0)
            workspaceActiveBackground = rgba(0,0,0,0)
            hideBackgroundLayers = false
            affectStrut = false
            overrideAnimSpeed = 1
            exitOnClick = true
            autoDrag = false
          }
```

**Comment by myamusashi** [comment]
```
plugin { 
    # Hyprspace configuration
    overview {
        # Color workspaces window
	  dragAlpha = 0.5
	  panelColor = rgba(30, 30, 46, 0.8)
	  panelBorderColor = rgb(243, 139, 168)
	  workspaceActiveBackground = rgba(14017025)

        # Layout
          workspaceMargin = 20
          panelHeight = 200
	  panelBorderWidth = 5
          workspaceBorderSize = 5
          hideBackgroundLayers = 0
          onBottom = 1
	  overrideGaps = 1
          adaptiveHeight = 1
          centerAligned = true

        # Event 
          autoDrag = 1
          autoScroll = 1
	  drawActiveWorkspace = 1
  	  showNewWorkspace = 0
	  showEmptyWorkspace = 1
          showSpecialWorkspace = 0
          exitOnClick = 0

        # Animation 
          overrideAnimSpeed = 8
}
```

**Comment by aacebedo** [comment]
Thanks.
I tested your config and same effect. The panelColor is always black and does not have any alpha.
Which version of hyprland and the plugin are you using ?

**Comment by aacebedo** [comment]
Ok so something is wrong in the rest of my hyprland config I guess.
Could you post an example of a working config ? You are using hyprpaper for the background too?

**Comment by myamusashi** [comment]
Nah, i'm using swww

**Comment by myamusashi** [comment]
Add this to your hyprland.conf

opengl {
  force_introspection = 1
}

**Comment by aacebedo** [comment]
That did the trick! Thanks!
